Updating asmdef name entry

diff --git a/.github/workflows/rename.yml b/.github/workflows/rename.yml
--- a/.github/workflows/rename.yml
+++ b/.github/workflows/rename.yml
@@ -50,31 +50,67 @@ jobs:
           field: displayName
           value: ${{ inputs.package-name }}
 
-
-
-      - name: Gather Assembly Definition paths
-        id: asmdef-paths
+      - name: Rename assembly definition files
+        id: rename-asmdef
         run: |
-          function find_asmdef() {
-            local TARGET_DIRECTORY="$1"
+          function rename_asmdef_in_directory() {
+            local DIRECTORY="$1"
 
-            if ! [ -d "$TARGET_DIRECTORY" ]; then
-              echo ""
+            if ! [ -d "$DIRECTORY" ]; then
+              echo "Notice: Directory expected to contain a '.asmdef' file, '$DIRECTORY' does not exits." >&2
+              return
+            fi
+            
+            local CURRENT_PATH=$(find "$DIRECTORY" -maxdepth 1 -name "*.asmdef" -print -quit)
+            if ! [ -d "$CURRENT_PATH" ]; then
+              echo "Notice: Expected '.asmdef' files was not found in directory '$DIRECTORY'." >&2
               return
             fi
 
-            echo find "$TARGET_DIRECTORY" -name "*.asmdef" -print -quit
+            local NEW_NAME="$2"
+            local NEW_PATH=$(dirname "$CURRENT_PATH")/NEW_NAME
+
+            mv $CURRENT_PATH $NEW_PATH
+            echo "Renamed '$CURRENT_PATH' to '$NEW_PATH'." >&2
+
+            echo $NEW_PATH
           }
           
-          echo "runtime=$(find_asmdef "Runtime")" >> GITHUB_OUTPUT
-          echo "editor=$(find_asmdef "Editor")" >> GITHUB_OUTPUT
-          echo "runtime-tests=$(find_asmdef "Tests/Runtime")" >> GITHUB_OUTPUT
-          echo "editor-tests=$(find_asmdef "Tests/Editor")" >> GITHUB_OUTPUT
+          ASMDEF_BASE_NAME=${{ inputs.company-name }}.${{ inputs.package-name }}
+
+          echo "runtime=$(rename_asmdef_in_directory "Runtime" "$ASMDEF_BASE_NAME")" >> GITHUB_OUTPUT
+          echo "editor=$(rename_asmdef_in_directory "Editor" "$ASMDEF_BASE_NAME.Editor")" >> GITHUB_OUTPUT
+          echo "runtime-tests=$(rename_asmdef_in_directory "Tests/Runtime" "$ASMDEF_BASE_NAME.Tests")" >> GITHUB_OUTPUT
+          echo "editor-tests=$(rename_asmdef_in_directory "Tests/Editor" "$ASMDEF_BASE_NAME.Editor.Tests")" >> GITHUB_OUTPUT
 
       - name: Update Runtime assembly definition name
-        if: steps.asmdef-paths.outputs.asmdef != ''
+        if: steps.rename-asmdef.outputs.runtime != ''
         uses: jossef/action-set-json-field@v2
         with:
-          file: ${{ steps.asmdef-paths.outputs.runtime }}
+          file: ${{ steps.rename-asmdef.outputs.runtime }}
           field: name
-          value: "${{ inputs.company-name }}/${{ inputs.package-name }}"
+          value: "${{ inputs.company-name }}.${{ inputs.package-name }}"
+
+      - name: Update Editor assembly definition name
+        if: steps.rename-asmdef.outputs.editor != ''
+        uses: jossef/action-set-json-field@v2
+        with:
+          file: ${{ steps.rename-asmdef.outputs.editor }}
+          field: name
+          value: "${{ inputs.company-name }}.${{ inputs.package-name }}.Editor"
+
+      - name: Update Runtime Tests assembly definition name
+        if: steps.rename-asmdef.outputs.runtime-tests != ''
+        uses: jossef/action-set-json-field@v2
+        with:
+          file: ${{ steps.rename-asmdef.outputs.runtime-tests }}
+          field: name
+          value: "${{ inputs.company-name }}.${{ inputs.package-name }}.Tests"
+
+      - name: Update Editor Tests assembly definition name
+        if: steps.rename-asmdef.outputs.editor-tests != ''
+        uses: jossef/action-set-json-field@v2
+        with:
+          file: ${{ steps.rename-asmdef.outputs.editor-tests }}
+          field: name
+          value: "${{ inputs.company-name }}.${{ inputs.package-name }}.Editor.Tests"
